### ISSUE TITLE
Расписание РТУ МИРЭА филиала Фрязино

### ISSUE THREAD

**Issue by makbeaver** [serguun42/mss#159]
Добрый день. Можно ли добавить на сайт расписание групп филиала Фрязино. Пытался найти ФКБО-01-22, но ее нет.

**Comment by serguun42** [comment]
Посмотрел сайт филиала, формат таблиц – такой же, как и на [mirea.ru/schedule](https://www.mirea.ru/schedule), не слишком много надо переписывать (только другую иерархию страниц). Поэтому постараюсь добавить в ближайшее время.

**Comment by makbeaver** [comment]
Буду крайне признателен.

**Comment by serguun42** [comment]
Добавил поддержку филиала Фрязино, доступны все группы, в [т.ч. ФКБО-01-22](https://mirea.xyz/group?name=%D0%A4%D0%9A%D0%91%D0%9E-01-22&suffix=%D0%A4%D0%B8%D0%BB%D0%B8%D0%B0%D0%BB%20%D0%A0%D0%A2%D0%A3%20%D0%9C%D0%98%D0%A0%D0%AD%D0%90%20%D0%B2%20%D0%B3.%20%D0%A4%D1%80%D1%8F%D0%B7%D0%B8%D0%BD%D0%BE). Расписание автоматически обновляется каждые полчаса, что для главной организации, что для филиала: изменится на сайте – сразу изменится и у нас.

Напоминаю, что кроме сайта [mirea.xyz](https://mirea.xyz) у нас есть [Telegram-бот](https://t.me/mirea_table_bot) и [Android-приложение](https://mirea.xyz/app), рекомендую ознакомится. Так же на сайте в футере можно сделать экспорт расписания в календарь (формат `.ics`)

**Comment by makbeaver** [comment]
Огромное спасибо Вам!
