### ISSUE TITLE
Telegram bot groups support

### ISSUE THREAD

**Issue by makbeaver** [serguun42/mss#204]
Добрый день. Есть возможность сделать так, чтоб бот мог работать в группе?

**Comment by serguun42** [comment]
Бот уже доступен для работы в группах. Вот как можно его активировать и настроить:

1. Добавьте бота в группу. Юзернейм – [@mirea_table_bot](https://t.me/mirea_table_bot)
2. Напишите в группе команду `/start@mirea_table_bot`
3. На отправленное ботом сообщение ответьте номером группы, которую хотите прикрепить (позже её можно поменять)
4. После установки группы вы сможете настроить рассылку (_или отключить её_).

**Важно:** все взаимодействия с ботом в группе совершайте через кнопки (под полем ввода) или отвечая на сообщения бота. У бота активирован режим приватности – https://core.telegram.org/bots/features#privacy-mode – т.е. ему доступны только те сообщения, что отправлены через его же кнопки, или реплаи ему. Админские права боту лучше не выдавать.

На скринах, что описал выше

![image](https://user-images.githubusercontent.com/27496498/195162464-d5b55822-4d49-4855-9472-a969a8732fb6.png)
![image](https://user-images.githubusercontent.com/27496498/195162736-cd58f685-b61d-43f6-9c78-8b5943c259ef.png)

**Comment by makbeaver** [comment]
Большое спасибо за помощь!
